import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const clientSource = readFileSync(new URL('../api/piMemoryClient.js', import.meta.url), 'utf8');
const panelSource = readFileSync(new URL('./PiMemoryPanel.jsx', import.meta.url), 'utf8');
const sectionsSource = readFileSync(new URL('./AssistantSettingsSections.jsx', import.meta.url), 'utf8');

test('PI memory panel exposes review, promotion, edit, disable, and delete controls', () => {
  assert.match(sectionsSource, /import PiMemoryPanel from '\.\/PiMemoryPanel'/);
  assert.match(sectionsSource, /<PiMemoryPanel \/>/);
  assert.match(clientSource, /list:\s*\(filter = \{\}\)/);
  assert.match(clientSource, /create:\s*\(memory\)/);
  assert.match(clientSource, /pin:\s*\(id\)/);
  assert.match(clientSource, /forget:\s*\(id\)/);
  assert.match(clientSource, /promote:\s*\(id\)/);
  assert.match(clientSource, /disable:\s*\(id\)/);
  assert.match(clientSource, /update:\s*\(id, updates\)/);
  assert.match(clientSource, /remove:\s*\(id\)/);
  assert.match(panelSource, /piMemoryApi\.create\(state\.newDraft\)/);
  assert.match(panelSource, /piMemoryApi\.pin\(item\.id\)/);
  assert.match(panelSource, /piMemoryApi\.forget\(item\.id\)/);
  assert.match(panelSource, /piMemoryApi\.promote\(item\.id\)/);
  assert.match(panelSource, /piMemoryApi\.disable\(item\.id\)/);
  assert.match(panelSource, /piMemoryApi\.update\(item\.id/);
  assert.match(panelSource, /piMemoryApi\.remove\(item\.id\)/);
  assert.match(panelSource, /手动添加/);
  assert.match(panelSource, /memory_type/);
  assert.match(panelSource, /citation_label/);
  assert.match(panelSource, /引用对象/);
  assert.match(panelSource, /activeCount/);
  assert.match(panelSource, /candidateCount/);
  assert.match(panelSource, /recentCandidateSource/);
  assert.match(panelSource, /Runner Chat \/ manager cycle \/ supervisor/);
  assert.match(panelSource, /failure-pattern generator/);
  assert.match(panelSource, /memory_write_candidate/);
  assert.match(panelSource, /明确授权的低风险个人偏好可自动启用/);
  assert.match(panelSource, /推断、敏感、低置信度、项目\/团队策略仍会保留为候选/);
  assert.match(panelSource, /可随时禁用或删除已启用记忆/);
  assert.doesNotMatch(panelSource, /window\.confirm/);
  assert.doesNotMatch(panelSource, /window\.alert/);
});
