import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const clientSource = readFileSync(new URL('../api/piMemoryClient.js', import.meta.url), 'utf8');
const panelSource = readFileSync(new URL('./PiMemoryPanel.jsx', import.meta.url), 'utf8');
const sectionsSource = readFileSync(new URL('./AssistantSettingsSections.jsx', import.meta.url), 'utf8');

test('PI memory panel exposes automatic reusable memory management without a review queue', () => {
  assert.match(sectionsSource, /import PiMemoryPanel from '\.\/PiMemoryPanel'/);
  assert.match(sectionsSource, /<PiMemoryPanel \/>/);
  assert.match(clientSource, /list:\s*\(filter = \{\}\)/);
  assert.match(clientSource, /create:\s*\(memory\)/);
  assert.match(clientSource, /pin:\s*\(id\)/);
  assert.match(clientSource, /forget:\s*\(id\)/);
  assert.match(clientSource, /enable:\s*\(id\)/);
  assert.doesNotMatch(clientSource, /promote:\s*\(id\)/);
  assert.match(clientSource, /disable:\s*\(id\)/);
  assert.match(clientSource, /update:\s*\(id, updates\)/);
  assert.match(panelSource, /Supervisor Memory/);
  assert.match(panelSource, /PI 自动记住可复用的偏好、决策、工作方法、Bug 根因、修复方式和验证经验/);
  assert.match(panelSource, /当前 Work \/ Run \/ Issue 状态永远以实时查询为准/);
  assert.match(panelSource, /相同 memory_key 会更新而不是重复追加/);
  assert.match(panelSource, /记忆自动生效，不需要逐条人工审核/);
  assert.match(panelSource, /memory_key/);
  assert.match(panelSource, /occurrence_count/);
  assert.match(panelSource, /last_seen_at/);
  assert.match(panelSource, /piMemoryApi\.create/);
  assert.match(panelSource, /piMemoryApi\.pin/);
  assert.match(panelSource, /piMemoryApi\.forget/);
  assert.match(panelSource, /piMemoryApi\.enable/);
  assert.doesNotMatch(panelSource, /piMemoryApi\.promote/);
  assert.match(panelSource, /piMemoryApi\.disable/);
  assert.match(panelSource, /piMemoryApi\.update/);
  assert.doesNotMatch(panelSource, /batch review/);
  assert.doesNotMatch(panelSource, /Candidate memory/);
  assert.doesNotMatch(panelSource, /Daily\/Weekly digest/);
  assert.doesNotMatch(panelSource, /window\.confirm/);
  assert.doesNotMatch(panelSource, /window\.alert/);
});
