import type { RunnerDatabase } from "../db/database.ts";

export const APP_LANGUAGES = ["zh-CN", "en-US"] as const;
export type AppLanguage = typeof APP_LANGUAGES[number];

export const DEFAULT_APP_LANGUAGE: AppLanguage = "zh-CN";
export const APP_LANGUAGE_PREFERENCE_KEY = "app.language";

export function appLanguage(db: RunnerDatabase): AppLanguage {
  const row = db.sqlite.query<{ value: unknown }, [string]>(
    "select value from app_preferences where key=?"
  ).get(APP_LANGUAGE_PREFERENCE_KEY);
  return normalizeAppLanguage(row?.value);
}

export function saveAppLanguage(db: RunnerDatabase, value: unknown, now = new Date()): AppLanguage {
  const language = parseAppLanguage(value);
  db.sqlite.run(
    `insert into app_preferences (key, value, updated_at) values (?, ?, ?)
     on conflict(key) do update set value=excluded.value, updated_at=excluded.updated_at`,
    [APP_LANGUAGE_PREFERENCE_KEY, language, now.toISOString()]
  );
  return language;
}

export function normalizeAppLanguage(value: unknown): AppLanguage {
  const normalized = typeof value === "string" ? value.trim().toLowerCase() : "";
  if (normalized === "en" || normalized.startsWith("en-")) return "en-US";
  if (normalized === "zh" || normalized.startsWith("zh-")) return "zh-CN";
  return DEFAULT_APP_LANGUAGE;
}

export function parseAppLanguage(value: unknown): AppLanguage {
  if (value === "zh-CN" || value === "en-US") return value;
  throw new Error("language must be zh-CN or en-US");
}

export function inferAppLanguageFromText(value: unknown, fallback: AppLanguage): AppLanguage {
  const text = typeof value === "string" ? value.trim() : "";
  if (text === "") return fallback;
  const han = text.match(/\p{Script=Han}/gu)?.length ?? 0;
  const latin = text.match(/[A-Za-z]/g)?.length ?? 0;
  if (han >= 2) return "zh-CN";
  if (latin >= 2) return "en-US";
  return fallback;
}

export function piLanguageContract(language: AppLanguage): string {
  if (language === "en-US") {
    return [
      "Language contract: the current system language is English (en-US).",
      "All user-facing natural-language replies, summaries, clarification questions, rationale, recovery_message, message, and expected_outcome fields generated by the model must be in English, even when quoted input or the user's latest message uses another language.",
      "Keep code identifiers, commands, file paths, logs, enum values, JSON keys, and verbatim evidence in their original language. This system language takes precedence over language inference from the latest message."
    ].join(" ");
  }
  return [
    "语言合同：当前系统语言为简体中文（zh-CN）。",
    "模型生成的所有面向用户的自然语言回答、摘要、澄清问题，以及 rationale、recovery_message、message、expected_outcome 等文本字段都必须使用简体中文，即使引用材料或用户最近一条消息使用其他语言。",
    "代码标识符、命令、文件路径、日志、枚举值、JSON key 与逐字证据保持原文。系统语言优先于根据最近消息推断出的语言。"
  ].join("");
}
